AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: {{cookiecutter.project_name.lower().replace(' ', '-')}} aws
Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Default: {{cookiecutter.enviroment.lower().replace(' ', '-')}}
    Description: Environment
    Type: String
  LogLevel:
    Default: DEBUG
    Description: Log level for lambda code
    Type: String
      
Resources:
  {{cookiecutter.lambda_name.lower().replace(' ', '-')}}:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:22
      CodeUri: service/
      Handler: app.lambda_handler
      Runtime: python3.9
          